<?php

return [
    'LANGUAGE_BG' => 'bg',
    'LANGUAGE_EN' => 'en',

    'THUMB_WIDTH' => 393,
    'THUMB_HEIGHT' => 216,

    'ARTICLE_WAITING_APPROVAL' => 0,
    'ARTICLE_PRIVATE' => 1,
    'ARTICLE_PUBLIC' => 2,

    'PAGE_STATUS_DRAFT' => 0,
    'PAGE_STATUS_PUBLIC' => 2,

    'USER_ROLE_CLIENT' => 1,
    'USER_ROLE_SUPPLIER' => 2,
    'USER_ROLE_ADMIN' => 999,

    'ADMIN_ACCESS_ARTICLES' => 7,
    'ADMIN_ACCESS_STATIC_PAGES' => 8,
    'ADMIN_ACCESS_FEEDBACK' => 9,
    'ADMIN_ACCESS_SETTINGS' => 10,
    'ADMIN_ACCESS_USERS' => 11,
    'ADMIN_ACCESS_SERVICES' => 12,
    'ADMIN_ACCESS_STATS' => 13,
];
